#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=on
	active_color="gradient(top_left=0xff00BFFF,bottom_right=0xc07FFFAA)"	
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
)

borders "${options[@]}"
